use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :invault, InvaultWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :invault, Invault.Repo,
  username: "postgres",
  password: "postgres",
  database: "invault_dev",
  hostname: "localhost",
  pool_size: 10

config :invault, Invault.Mailer, adapter: Bamboo.LocalAdapter
config :invault, Invault.CurrentTime, adapter: Invault.CurrentTime.SystemAdapter

config :invault, Invault.Accounts.Registration,
  pepper:
    "NUITuUCAclDannvrsnuh7Gp_IaogIx5j9hZBlc_XuXt7VvyQCm9LE9Q5w7YCfoHqNcz29sNOA_bkufN-duewvmABhsrpfP6cDFWUkJos-8NkpqjyRm5c0MBTHud2lOlU"
